-- Gruber Darker — Neovim port of the Gruber Darker theme by Jason Blevins / rexim
-- https://github.com/rexim/gruber-darker-theme

vim.cmd("hi clear")
vim.g.colors_name = "gruber-darker"
vim.o.background = "dark"

local c = {
  bg_1 = "#121212",
  bg = "#181818",
  bg1 = "#2e2e2e",
  bg2 = "#453d41",
  bg3 = "#484848",
  bg4 = "#52494e",
  fg = "#c8c8d0",
  fg1 = "#d8d8e0",
  fg2 = "#e0e0e0",
  white = "#d8d8e0",
  black = "#1a1a1a",
  red_1 = "#a63538",
  red = "#cc4444",
  red1 = "#d95555",
  green = "#5ea330",
  yellow = "#d4b83a",
  brown = "#b07a38",
  quartz = "#7e9189",
  niagara_1 = "#5f627f",
  niagara = "#8298b5",
  wisteria = "#8a83ab",
}

local hl = function(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

-- Editor
hl("Normal", { fg = c.fg, bg = c.bg })
hl("NormalFloat", { fg = c.fg, bg = c.bg_1 })
hl("FloatBorder", { fg = c.bg4, bg = c.bg_1 })
hl("FloatTitle", { fg = c.yellow, bg = c.bg_1, bold = true })
hl("Cursor", { fg = c.black, bg = c.yellow })
hl("lCursor", { link = "Cursor" })
hl("CursorIM", { link = "Cursor" })
hl("CursorLine", { bg = c.bg1 })
hl("CursorColumn", { bg = c.bg1 })
hl("ColorColumn", { bg = c.bg1 })
hl("LineNr", { fg = c.bg4 })
hl("CursorLineNr", { fg = c.yellow })
hl("SignColumn", { fg = c.bg4, bg = c.bg })
hl("FoldColumn", { fg = c.bg4, bg = c.bg })
hl("Folded", { fg = c.brown, bg = c.bg1 })
hl("VertSplit", { fg = c.bg3 })
hl("WinSeparator", { fg = c.bg3 })
hl("Visual", { bg = c.bg3 })
hl("VisualNOS", { bg = c.bg3 })
hl("Search", { fg = c.black, bg = c.yellow })
hl("IncSearch", { fg = c.black, bg = c.yellow })
hl("CurSearch", { fg = c.black, bg = c.yellow })
hl("Substitute", { fg = c.black, bg = c.red })
hl("MatchParen", { fg = c.fg, bg = c.bg2, bold = true })
hl("NonText", { fg = c.bg3 })
hl("SpecialKey", { fg = c.bg3 })
hl("Whitespace", { fg = c.bg3 })
hl("EndOfBuffer", { fg = c.bg })
hl("Conceal", { fg = c.niagara })
hl("Directory", { fg = c.niagara })
hl("Title", { fg = c.yellow, bold = true })
hl("ErrorMsg", { fg = c.red, bold = true })
hl("WarningMsg", { fg = c.brown })
hl("ModeMsg", { fg = c.fg, bold = true })
hl("MoreMsg", { fg = c.niagara })
hl("Question", { fg = c.niagara })
hl("StatusLine", { fg = c.white, bg = c.bg1 })
hl("StatusLineNC", { fg = c.bg4, bg = c.bg1 })
hl("TabLine", { fg = c.bg4, bg = c.bg1 })
hl("TabLineFill", { bg = c.bg_1 })
hl("TabLineSel", { fg = c.yellow, bg = c.bg })
hl("WinBar", { fg = c.fg, bg = c.bg })
hl("WinBarNC", { fg = c.bg4, bg = c.bg })
hl("Pmenu", { fg = c.fg, bg = c.bg_1 })
hl("PmenuSel", { bg = c.bg3 })
hl("PmenuSbar", { bg = c.bg1 })
hl("PmenuThumb", { bg = c.bg4 })
hl("WildMenu", { fg = c.black, bg = c.yellow })
hl("SpellBad", { sp = c.red, undercurl = true })
hl("SpellCap", { sp = c.brown, undercurl = true })
hl("SpellLocal", { sp = c.niagara, undercurl = true })
hl("SpellRare", { sp = c.wisteria, undercurl = true })
hl("DiffAdd", { bg = "#1a2e1a" })
hl("DiffChange", { bg = "#1a1a2e" })
hl("DiffDelete", { bg = "#2e1a1a" })
hl("DiffText", { bg = "#2a2a4a" })

-- Syntax
hl("Comment", { fg = c.brown, italic = true })
hl("Constant", { fg = c.quartz })
hl("String", { fg = c.green })
hl("Character", { fg = c.green })
hl("Number", { fg = c.wisteria })
hl("Float", { fg = c.wisteria })
hl("Boolean", { fg = c.yellow })
hl("Identifier", { fg = c.fg })
hl("Function", { fg = c.niagara })
hl("Statement", { fg = c.yellow })
hl("Conditional", { fg = c.yellow })
hl("Repeat", { fg = c.yellow })
hl("Label", { fg = c.yellow })
hl("Operator", { fg = c.fg })
hl("Keyword", { fg = c.yellow })
hl("Exception", { fg = c.yellow })
hl("PreProc", { fg = c.quartz })
hl("Include", { fg = c.yellow })
hl("Define", { fg = c.yellow })
hl("Macro", { fg = c.yellow })
hl("PreCondit", { fg = c.yellow })
hl("Type", { fg = c.quartz })
hl("StorageClass", { fg = c.yellow })
hl("Structure", { fg = c.quartz })
hl("Typedef", { fg = c.quartz })
hl("Special", { fg = c.yellow })
hl("SpecialChar", { fg = c.yellow })
hl("Tag", { fg = c.yellow })
hl("Delimiter", { fg = c.fg })
hl("SpecialComment", { fg = c.brown })
hl("Debug", { fg = c.red })
hl("Underlined", { fg = c.niagara, underline = true })
hl("Error", { fg = c.red })
hl("Todo", { fg = c.yellow, bold = true })

-- Treesitter
hl("@variable", { fg = c.fg })
hl("@variable.builtin", { fg = c.yellow })
hl("@variable.parameter", { fg = c.fg1 })
hl("@variable.member", { fg = c.fg })
hl("@constant", { fg = c.quartz })
hl("@constant.builtin", { fg = c.quartz })
hl("@constant.macro", { fg = c.quartz })
hl("@module", { fg = c.fg })
hl("@string", { fg = c.green })
hl("@string.escape", { fg = c.yellow })
hl("@string.regex", { fg = c.wisteria })
hl("@string.special", { fg = c.wisteria })
hl("@character", { fg = c.green })
hl("@number", { fg = c.wisteria })
hl("@number.float", { fg = c.wisteria })
hl("@boolean", { fg = c.yellow })
hl("@function", { fg = c.niagara })
hl("@function.builtin", { fg = c.niagara })
hl("@function.call", { fg = c.niagara })
hl("@function.macro", { fg = c.yellow })
hl("@function.method", { fg = c.niagara })
hl("@function.method.call", { fg = c.niagara })
hl("@constructor", { fg = c.niagara })
hl("@operator", { fg = c.fg })
hl("@keyword", { fg = c.yellow })
hl("@keyword.coroutine", { fg = c.yellow })
hl("@keyword.function", { fg = c.yellow })
hl("@keyword.operator", { fg = c.yellow })
hl("@keyword.import", { fg = c.yellow })
hl("@keyword.type", { fg = c.yellow })
hl("@keyword.modifier", { fg = c.yellow })
hl("@keyword.repeat", { fg = c.yellow })
hl("@keyword.return", { fg = c.yellow })
hl("@keyword.exception", { fg = c.yellow })
hl("@keyword.conditional", { fg = c.yellow })
hl("@keyword.directive", { fg = c.quartz })
hl("@punctuation.bracket", { fg = c.fg })
hl("@punctuation.delimiter", { fg = c.fg })
hl("@punctuation.special", { fg = c.yellow })
hl("@comment", { fg = c.brown, italic = true })
hl("@comment.documentation", { fg = c.brown, italic = true })
hl("@comment.todo", { fg = c.yellow, bold = true })
hl("@comment.warning", { fg = c.red, bold = true })
hl("@comment.error", { fg = c.red, bold = true })
hl("@comment.note", { fg = c.niagara, bold = true })
hl("@type", { fg = c.quartz })
hl("@type.builtin", { fg = c.yellow })
hl("@type.definition", { fg = c.quartz })
hl("@type.qualifier", { fg = c.yellow })
hl("@attribute", { fg = c.quartz })
hl("@property", { fg = c.fg })
hl("@tag", { fg = c.yellow })
hl("@tag.attribute", { fg = c.niagara })
hl("@tag.delimiter", { fg = c.bg4 })
hl("@markup.heading", { fg = c.yellow, bold = true })
hl("@markup.strong", { bold = true })
hl("@markup.italic", { italic = true })
hl("@markup.strikethrough", { strikethrough = true })
hl("@markup.underline", { underline = true })
hl("@markup.raw", { fg = c.green })
hl("@markup.link", { fg = c.niagara, underline = true })
hl("@markup.link.url", { fg = c.niagara, underline = true })
hl("@markup.list", { fg = c.yellow })

-- LSP Semantic Tokens
hl("@lsp.type.class", { fg = c.quartz })
hl("@lsp.type.decorator", { fg = c.quartz })
hl("@lsp.type.enum", { fg = c.quartz })
hl("@lsp.type.enumMember", { fg = c.quartz })
hl("@lsp.type.function", { fg = c.niagara })
hl("@lsp.type.interface", { fg = c.quartz })
hl("@lsp.type.macro", { fg = c.yellow })
hl("@lsp.type.method", { fg = c.niagara })
hl("@lsp.type.namespace", { fg = c.fg })
hl("@lsp.type.parameter", { fg = c.fg1 })
hl("@lsp.type.property", { fg = c.fg })
hl("@lsp.type.struct", { fg = c.quartz })
hl("@lsp.type.type", { fg = c.quartz })
hl("@lsp.type.typeParameter", { fg = c.quartz })
hl("@lsp.type.variable", { fg = c.fg })

-- Diagnostics
hl("DiagnosticError", { fg = c.red })
hl("DiagnosticWarn", { fg = c.brown })
hl("DiagnosticInfo", { fg = c.niagara })
hl("DiagnosticHint", { fg = c.quartz })
hl("DiagnosticOk", { fg = c.green })
hl("DiagnosticUnderlineError", { sp = c.red, undercurl = true })
hl("DiagnosticUnderlineWarn", { sp = c.brown, undercurl = true })
hl("DiagnosticUnderlineInfo", { sp = c.niagara, undercurl = true })
hl("DiagnosticUnderlineHint", { sp = c.quartz, undercurl = true })
hl("DiagnosticVirtualTextError", { fg = c.red, bg = "#2a1818" })
hl("DiagnosticVirtualTextWarn", { fg = c.brown, bg = "#2a2218" })
hl("DiagnosticVirtualTextInfo", { fg = c.niagara, bg = "#18182a" })
hl("DiagnosticVirtualTextHint", { fg = c.quartz, bg = "#1a2220" })

-- Git signs
hl("GitSignsAdd", { fg = c.green })
hl("GitSignsChange", { fg = c.niagara })
hl("GitSignsDelete", { fg = c.red })

-- Telescope
hl("TelescopeNormal", { fg = c.fg, bg = c.bg_1 })
hl("TelescopeBorder", { fg = c.bg3, bg = c.bg_1 })
hl("TelescopeTitle", { fg = c.yellow, bold = true })
hl("TelescopePromptNormal", { fg = c.fg, bg = c.bg1 })
hl("TelescopePromptBorder", { fg = c.bg1, bg = c.bg1 })
hl("TelescopePromptTitle", { fg = c.yellow, bg = c.bg1, bold = true })
hl("TelescopeSelection", { bg = c.bg3 })
hl("TelescopeMatching", { fg = c.yellow, bold = true })

-- Snacks picker / dashboard
hl("SnacksPickerNormal", { fg = c.fg, bg = c.bg_1 })
hl("SnacksPickerBorder", { fg = c.bg3, bg = c.bg_1 })
hl("SnacksPickerTitle", { fg = c.yellow, bold = true })
hl("SnacksPickerMatch", { fg = c.yellow, bold = true })
hl("SnacksDashboardHeader", { fg = c.yellow })
hl("SnacksDashboardFooter", { fg = c.brown, italic = true })
hl("SnacksDashboardKey", { fg = c.yellow })
hl("SnacksDashboardDesc", { fg = c.fg })
hl("SnacksDashboardIcon", { fg = c.niagara })

-- Indent / scope
hl("IblIndent", { fg = c.bg1 })
hl("IblScope", { fg = c.bg4 })

-- Noice / Notify
hl("NoiceCmdlinePopup", { fg = c.fg, bg = c.bg_1 })
hl("NoiceCmdlinePopupBorder", { fg = c.bg3 })
hl("NotifyERRORBorder", { fg = c.red })
hl("NotifyWARNBorder", { fg = c.brown })
hl("NotifyINFOBorder", { fg = c.niagara })
hl("NotifyDEBUGBorder", { fg = c.bg4 })
hl("NotifyTRACEBorder", { fg = c.wisteria })
hl("NotifyERRORTitle", { fg = c.red })
hl("NotifyWARNTitle", { fg = c.brown })
hl("NotifyINFOTitle", { fg = c.niagara })
hl("NotifyDEBUGTitle", { fg = c.bg4 })
hl("NotifyTRACETitle", { fg = c.wisteria })
hl("NotifyERRORIcon", { fg = c.red })
hl("NotifyWARNIcon", { fg = c.brown })
hl("NotifyINFOIcon", { fg = c.niagara })
hl("NotifyDEBUGIcon", { fg = c.bg4 })
hl("NotifyTRACEIcon", { fg = c.wisteria })

-- Which-key
hl("WhichKey", { fg = c.yellow })
hl("WhichKeyGroup", { fg = c.niagara })
hl("WhichKeyDesc", { fg = c.fg })
hl("WhichKeySeparator", { fg = c.brown })

-- Lazy
hl("LazyH1", { fg = c.black, bg = c.yellow, bold = true })
hl("LazyButton", { fg = c.fg, bg = c.bg1 })
hl("LazyButtonActive", { fg = c.black, bg = c.yellow })
hl("LazySpecial", { fg = c.yellow })

-- Mini (statusline, etc.)
hl("MiniStatuslineFilename", { fg = c.fg, bg = c.bg1 })
hl("MiniStatuslineDevinfo", { fg = c.quartz, bg = c.bg1 })
hl("MiniStatuslineModeNormal", { fg = c.black, bg = c.yellow, bold = true })
hl("MiniStatuslineModeInsert", { fg = c.black, bg = c.green, bold = true })
hl("MiniStatuslineModeVisual", { fg = c.black, bg = c.wisteria, bold = true })
hl("MiniStatuslineModeReplace", { fg = c.black, bg = c.red, bold = true })
hl("MiniStatuslineModeCommand", { fg = c.black, bg = c.brown, bold = true })
